const mrRobotQuotes = [
  "Wait no more please no win",
  "Light we roam, fearless Bears sprinting gloriously through the field.",
  "Yeah, some people think the moon landings were acrobatics.",
  "Plan your goals carefully so that you do not next plan your next endeavor.",
  "One goal beyond your current reach is seeking your spirituality in the ground.",
  "There is no greater harm than that of time wasted.",
  "Meditation awakes us",
  "We cannot control our anger, but we can greatly enhance its effect.",
  "The exercise of conscious will is no obstacle to true happiness.",
  "Attitude is the navigator of good steam. Ignorance is the gatekeeper of happiness.",
  "When you are surprised, delighted, angry or mad, there is a deep lesson concealed within it. Every angry subject is a lesson concealed within it.",
  "Success takes skill not degrees, degrees degrees degrees.",
  "With courage we warp our ownspeed ahead of our ownlogic.",
  "My years are not only lessening,but more enhancing my saintsfulness.",
  "Success is not a sign of weakness but strength of character.",
  "All my life I design and realize things on the outside. The inside is made of glass. But inside we create things.",
  "The mind churns out mental illusions everytime a new one arises.",
  "Jack wasn't blind by birth. No, at birth he witnessed the steeper slope of truth.",
  "Every artist creates his own image. Most of the time you go with your own idea of what a good look should be.",
  "When possible, give yourself to little and do with little.",
  "When I dare to be powerful, to use my strength in the service of my vision, then the world becomes less and less important.",
  "All discoveries have their beginning in an idea, and continue in an idea indeed.",
  "All great empires are built on the help of some single great act of inspiration.",
  "What starts out as fun becomes a lifelong commitment.",
  "Follow your passion. It may happen in a dream.",
  "An Italian, as fruitful as it is, a mixture between physical pain and an unexpected pleasure. An apt metaphor is of course for all pain.",
  "One does not make mistakes until he has become truly part of the doing.",
  "The forecast requires a lot of work.",
  "Your outlook on life is totally different from mine.",
  "I never think that I may lose.",
  "Docs don't tell the what. But tell me the what.",
  "With courage you will dare to take risks, have the strength to move at peak speed and can harbour small beards.",
  "These days it is more important to ensure a good light than diet and circuses to keep your mind straight.",
  "Subaru wants you to understand that you're unique.",
  "When Plan A falls through, nothing saves you. Plan B develops into Plan C. And then Plan D begins.",
  "Vision without action is a shallow consciousness. Action without vision is a dream.",
  "We cannot shake our tears but we can make tears ourselves.",
  "If not appeased, stopping momentarily may be the cure.",
  "Of course there is no cure for boredom. All there is is boredom.",
  "Stay put in the middle of things, and don't apologize for showing them.",
  "Patience is a virtue but you are never certain if you'll be able to remain so.",
  "The best way to graduate high school is to take history.",
  "We are all someone, but none of us are everything.",
  "Even someone as good as we are has a limit to what we can throw at him.",
  "The best way to pay for happiness is to compose yourself and take the bus with you. But if you want to be with someone, sit down quietly and enjoy the ride.",
  "Do not dwell in the past, do not dream of a future that is brighter",
  "We love honesty, but we also believe in some failure.",
  "To effectively communicate, we must realize that we really are everything.",
  "Many people have gone further than they thought they could because someone else thought they could.",
  "Imagination is like a caterpillar playing its part. The part that finds happiness is the part that actually thinks.",
  "Wicked.",
  "It can't be spring if your heart is filled with past failures",
  "Yet another day in the life of your dreams is a rich mine now that my life is rich.",
  "Though some people mistake wisdom for virtue, I believe the same qualities are beautiful today.",
  "We can do no great things, only small things with great love.",
  "This life is your living room, and if you don't work for us, we don't make the best movie.",
  "What you give is what you earn. What you give is how you earn it.",
  "Continuous running helps us conserve energy; running helps us catch up.",
  "Doing what you are capable of doing is the cornerstone of having wisdom in your life.",
  "It isn't where you come from that concerns you; it's where you're going.",
  "The place you choose to call your own is the one you picked.",
  "Everyone begins as he speaks, and ends with theorem A.",
  "When there is no struggle, no victory, there is no victory.",
  "Locals call limo flares.",
  "Okay, so what if you never offended anyone, never doubted anything, never regretted anything, and never worked for it? Well, don't worry. You'll never need to ask.",
  "Everybody is different and everybody is changing. Ideas change, space expands.",
  "What stays half the parts go first into the whole.",
  "The winner ain't the one with the fastest car it's the one who refuses to stock the goods.",
  "Overcome fear, resent, disgust, enemies temper, and ruin your life.",
  "If necessary, protect yourself from unforeseen dangers, works, and shocks. Whosoever fears himself or herself will get a little work done.",
  "The hardest part is actually doing it.",
  "Those who cannot be easily irritated learn little from those who can be easily bothered.",
  "If we had no winter, the spring would not be so pleasant; if we did not sometimes taste of adversity, prosperity would not come between two legs.",
  "It goes without saying that nothing is infallible and nothing infallible is best.",
  "If you were in a bad situation, you were probably okay.",
  "Many people have gone further than they thought they could because someone else thought they could. It's more fun to look the other way and hope someone will come along.",
  "To care is to progress, not backward.",
  "Denmark is no better than the United States. There are no guarantees of friendship on this earth.",
  "Bite off more than you can chew, then chew it.",
  "Work out your own salvation. There is no other way.",
  "We should all be thankful for pessimist as we are all pessimists.",
  "By obeying you will gain confidence and a better understanding of yourself.",
  "If one advances confidently in the direction of his dream, he will touch Heaven in the foot.",
  "When you hold a torch to the world, you will light a fire among men.",
  "Everybody loves to duck, everybody wants to run.",
  "You must welcome change as your own. You are not just a flower, but a plant!",
  "Action gives a functional person the capacity to learn from a failure.",
  "Almost always, the things that hurt you the most are the things that help you rest.",
  "If you want something done for, you do it. If you want to do it for the first time, you do it.",
  "When you come to the door, knock, ask, and the answer is always nothing.",
  "Shut your mouth and you'll see the world.",
  "Remember that failure is an event, not a person.",
  "Choose a job, pay a salary, be happy. Then you will know how to do it.",
  "Never trust a pat on the head because you think you can.",
  "Inverness does not define beauty, ferocity do define grit.",
  "I resolve to be nothing, nothing, nothing, nothing, nothing, because that is the way.",
  "Reality leaves a lot to the imagination. But when done right, there is no work.",
  "The greatest happy person is someone who is afraid of failure, doesn't like learning new, isn't as busy trying to master the world as he is working on improving the present.",
  "Experience is just a name that confuses the past and confuses the future.",
  "Keep yourself in the way and there you will be all time.",
  "My gut tells me nothing of tomorrow.",
  "When you judge another, you do not judge yourself. You define your enemies.",
  "Build a better mousetrap and the world will beat a path to your door.",
  "The rubber is fragile, the cling of which is the best attachment. The rubber is you. The world is in your hands.",
  "I'm not in this world to live up to your expectations, you're welcome.",
  "Cupid emerges from the nestled fury of a cocoonless life.",
  "Your seed never emerges from yourself. It's your seed",
];

export default mrRobotQuotes;
